export const VERSION = '0.1.0'

export * from './types'
export { parsePointer, readPointer, writePointer, deletePointer } from './pointer'
export { createRootScope, createCollectionScope, resolveRead, resolveWriteParts } from './scope'
export type { Scope, RootScope, CollectionScope } from './scope'
export { BUILTIN_FUNCTIONS } from './functions'
export type { RegisteredFunction } from './functions'
export { toThunk, resolveOnce } from './binding'
export type { BindingContext } from './binding'
export { resolveProps, createBasicCatalog } from './catalog'
export type { Catalog, CatalogEntry, PropThunks } from './catalog'
export { instantiateNode } from './instantiate'
export { SurfaceRegistry, mountSurface } from './surface'
export type { Surface } from './surface'
export { dispatch } from './dispatcher'
export type { DispatchOptions } from './dispatcher'
