export type { DirectFnComponentParams, EmitContext } from './emit/emit-context.ts'
export { collectBindings, createEmitContext } from './emit/emit-context.ts'
export { substituteBindings } from './emit/emit-substitution.ts'
export { emitTemplateCloneExpression, emitTemplateDecl } from './emit/template-decl.ts'
export { compileJsxToBlock } from './emit/emit-core.ts'
export { buildCreateTemplateMethod, lowerJsxInStatement } from './emit/emit-jsx-lowering.ts'
